import Image from "next/image";
import Link from "next/link";

import { ProductRail } from "@/components/product/ProductRail";
import type { HomepageData } from "@/domain/catalog";
import { getBrands, getGenerations, getModels, getModifications, getYears } from "@/lib/vehicles";

function Crumbs({ items }: { items: { href?: string; label: string }[] }) {
  return <nav aria-label="Хлебные крошки" className="flex flex-wrap gap-2 text-meta text-ink-2"><Link href="/">Главная</Link>{items.map((item) => <span key={item.label}>/ {item.href ? <Link className="hover:text-accent" href={item.href}>{item.label}</Link> : item.label}</span>)}</nav>;
}

export async function VehicleJourney({ homepage, path }: { homepage: HomepageData; path: string[] }) {
  const [brand, model, year, generation, modification] = path;
  const brandName = getBrands().find((item) => item.slug === brand)?.name;
  if (!brandName) return null;
  const models = await getModels(brand);
  const modelItem = models.find((item) => item.slug === model);
  const base = `/catalog/legkovye/${brand}`;

  if (!model) return <main className="container-site section-stack bg-surface-2 pb-12 pt-4"><section className="rounded-ui bg-white p-4 desktop:p-6"><Crumbs items={[{ href: base, label: brandName }, { label: "Выберите модель" }]} /><h1 className="mt-4 text-block font-bold text-ink">Выберите модель {brandName}</h1><div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-3 desktop:grid-cols-5">{models.map((item) => <Link className="rounded-ui p-3 text-body font-bold text-ink hover:bg-surface-2" href={`${base}/${item.slug}`} key={item.slug}>{item.name} ({item.generations.map((entry) => entry.code).join(", ")})</Link>)}</div></section></main>;
  if (!modelItem) return null;
  const years = await getYears(brand, model);
  if (!year) return <main className="container-site section-stack bg-surface-2 pb-12 pt-4"><section className="rounded-ui bg-white p-4 desktop:p-6"><Crumbs items={[{ href: base, label: brandName }, { href: `${base}/${model}`, label: modelItem.name }, { label: "Выберите год" }]} /><h1 className="mt-4 text-block font-bold text-ink">Выберите год выпуска</h1><div className="mt-4 flex flex-wrap gap-2">{years.map((item) => <Link className="rounded-ui bg-surface-2 px-3 py-2 text-body font-bold text-ink hover:bg-accent hover:text-white" href={`${base}/${model}/${item}`} key={item}>{item}</Link>)}</div></section></main>;
  const generations = (await getGenerations(brand, model)).filter((item) => Number(year) >= item.yearFrom && Number(year) <= (item.yearTo ?? 2026));
  if (!generation) return <main className="container-site section-stack bg-surface-2 pb-12 pt-4"><section className="rounded-ui bg-white p-4 desktop:p-6"><Crumbs items={[{ href: base, label: brandName }, { href: `${base}/${model}`, label: modelItem.name }, { href: `${base}/${model}/${year}`, label: year }, { label: "Выберите поколение" }]} /><h1 className="mt-4 text-block font-bold text-ink">Выберите поколение</h1><div className="mt-4 grid gap-2">{generations.map((item) => <Link className="rounded-ui bg-surface-2 p-3 text-body font-bold text-ink hover:bg-accent hover:text-white" href={`${base}/${model}/${year}/${item.slug}`} key={item.slug}>{item.name} ({item.yearFrom}–{item.yearTo ?? "н.в."})</Link>)}</div></section></main>;
  const generationItem = generations.find((item) => item.slug === generation);
  if (!generationItem) return null;
  const modifications = await getModifications(brand, model, generation);
  if (!modification) return <main className="container-site section-stack bg-surface-2 pb-12 pt-4"><section className="rounded-ui bg-white p-4 desktop:p-6"><Crumbs items={[{ href: base, label: brandName }, { href: `${base}/${model}`, label: modelItem.name }, { href: `${base}/${model}/${year}`, label: year }, { href: `${base}/${model}/${year}/${generation}`, label: generationItem.name }, { label: "Выберите модификацию" }]} /><h1 className="mt-4 text-block font-bold text-ink">Выберите модификацию</h1><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-body"><thead className="border-b border-line text-ink-2"><tr><th className="p-3">Модификация</th><th className="p-3">Выпуск</th><th className="p-3">Двигатель</th><th className="p-3">Л.с.</th><th className="p-3">Привод</th></tr></thead><tbody>{modifications.map((item) => <tr className="border-b border-line hover:bg-surface-2" key={item.slug}><td className="p-3"><Link className="font-bold text-ink" href={`${base}/${model}/${year}/${generation}/${item.slug}`}>{item.name}</Link></td><td className="p-3">{item.yearFrom}–{item.yearTo ?? "н.в."}</td><td className="p-3">{item.volume} · {item.fuel}</td><td className="p-3">{item.hp}</td><td className="p-3">{item.drive}</td></tr>)}</tbody></table></div></section></main>;
  const modificationItem = modifications.find((item) => item.slug === modification);
  if (!modificationItem) return null;
  const groups = ["Двигатель", "Тормозная система", "Подвеска и рулевое", "Трансмиссия", "Электрооборудование", "Охлаждение и отопление", "Кузов", "Интерьер", "Выхлопная система"];
  return <main className="container-site section-stack bg-surface-2 pb-12 pt-4"><section className="rounded-ui bg-white p-4 desktop:p-6"><Crumbs items={[{ href: base, label: brandName }, { href: `${base}/${model}`, label: modelItem.name }, { label: `${year} ${modificationItem.name}` }]} /><div className="mt-4 flex flex-col gap-4 md:flex-row"><div className="relative aspect-[16/9] w-full overflow-hidden rounded-ui md:w-1/3"><Image alt={`${brandName} ${modelItem.name}`} className="object-cover" fill sizes="(min-width:768px) 33vw, 100vw" src="/images/hero/mercedes-sedan-parts.png" /></div><div className="min-w-0 flex-1"><h1 className="text-block font-bold text-ink">{brandName} / {modelItem.name} ({generationItem.code}) / {year} / {modificationItem.name}</h1><p className="mt-3 text-body text-ink-2">{modificationItem.engine} · {modificationItem.volume} {modificationItem.fuel} · {modificationItem.hp} л.с. · {modificationItem.drive} привод · {modificationItem.body}</p><div className="mt-4 flex flex-wrap gap-2"><a className="inline-flex h-btn items-center rounded-ui border border-accent px-4 text-btn font-bold text-accent" href="#expert-request">Заявка на подбор</a><Link className="inline-flex h-btn items-center rounded-ui bg-accent px-4 text-btn font-bold text-white" href={`${base}/${model}`}>Сменить авто</Link></div></div></div></section><section className="grid gap-4 rounded-ui bg-white p-4 desktop:grid-cols-4 desktop:p-6"><aside><h2 className="text-lead font-bold text-ink">Узлы</h2><div className="mt-3 flex flex-col gap-2">{groups.map((group) => <a className="text-body text-ink-2 hover:text-accent" href={`#${group}`} key={group}>{group}</a>)}</div></aside><div className="grid gap-4 md:grid-cols-2 desktop:col-span-3 desktop:grid-cols-3">{groups.map((group) => <article id={group} key={group}><h3 className="text-body font-bold text-ink">{group}</h3><p className="mt-2 text-meta text-ink-2">Расходники · Комплектующие · Датчики · Крепёж</p><Link className="mt-3 inline-block text-body text-accent hover:underline" href={`/catalog/legkovye/tormoza?car=${brand}/${model}/${generation}/${modification}`}>Посмотреть все ›</Link></article>)}</div></section><section className="rounded-ui bg-white p-4 desktop:p-6"><ProductRail products={homepage.popularProducts} /></section></main>;
}
